# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mzap < Formula
  desc "Multiple target zap scanning"
  homepage "https://github.com/hahwul/mzap"
  url "https://github.com/hahwul/mzap/archive/refs/tags/v2.0.0.tar.gz"
  sha256 "c26293dba9740dc68b96b01f3914452026a771d3d2759da2aa27ea814d448edc"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/mzap"
  end

  test do
    system "{bin}/mzap", "version"
  end
end
