# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mzap < Formula
  desc "Multiple target ZAP scanning / mzap is a tool for scanning N*N in ZAP."
  homepage "https://www.hahwul.com"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hahwul/mzap/releases/download/v1.2.0/mzap_1.2.0_darwin_arm64.tar.gz"
      sha256 "17f49776428586151084aeee6fc780375a146b7cec3dc9cfa2bb17c78d50d745"

      def install
        bin.install "mzap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/mzap/releases/download/v1.2.0/mzap_1.2.0_darwin_amd64.tar.gz"
      sha256 "ef53267cde662a8d53d6296297a8c877205de5766c57b6605fe1563809a7b3d5"

      def install
        bin.install "mzap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/mzap/releases/download/v1.2.0/mzap_1.2.0_linux_armv6.tar.gz"
      sha256 "1056f95846dec76641387725291346fe4ba2565fc163caef7e7248733c2c45d4"

      def install
        bin.install "mzap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/mzap/releases/download/v1.2.0/mzap_1.2.0_linux_arm64.tar.gz"
      sha256 "56c21855b4417f5aec3f79d985b47d17b7d33614818dba0d16c11d80e5fc9d44"

      def install
        bin.install "mzap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/mzap/releases/download/v1.2.0/mzap_1.2.0_linux_amd64.tar.gz"
      sha256 "d49dc5f292b25ba9e6b4f21353cf700a9fdc111871d05e9fedb1ff361f4a645e"

      def install
        bin.install "mzap"
      end
    end
  end

  test do
    system "#{bin}/mzap version"
  end
end
