# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mzap < Formula
  desc "Multiple target zap scanning"
  homepage "https://github.com/hahwul/mzap"
  url "https://github.com/hahwul/mzap/archive/refs/tags/v2.1.0.tar.gz"
  sha256 "d5b0939efbfe9ada4384a938641a8d5f470bfb7b08c79c3e49a2b45d1dcde24d"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/mzap"
  end

  test do
    system "{bin}/mzap", "version"
  end
end
